// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: event_processing.proto

package event_processing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pipeline_data "project/grpc-proto/pipeline_data"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventProcessingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *EventProcessingResult) Reset() {
	*x = EventProcessingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_processing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventProcessingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProcessingResult) ProtoMessage() {}

func (x *EventProcessingResult) ProtoReflect() protoreflect.Message {
	mi := &file_event_processing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProcessingResult.ProtoReflect.Descriptor instead.
func (*EventProcessingResult) Descriptor() ([]byte, []int) {
	return file_event_processing_proto_rawDescGZIP(), []int{0}
}

func (x *EventProcessingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_event_processing_proto protoreflect.FileDescriptor

var file_event_processing_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x1a, 0x13, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x31, 0x0a, 0x15, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0x6e, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x12, 0x5c, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x23, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x27, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_event_processing_proto_rawDescOnce sync.Once
	file_event_processing_proto_rawDescData = file_event_processing_proto_rawDesc
)

func file_event_processing_proto_rawDescGZIP() []byte {
	file_event_processing_proto_rawDescOnce.Do(func() {
		file_event_processing_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_processing_proto_rawDescData)
	})
	return file_event_processing_proto_rawDescData
}

var file_event_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_processing_proto_goTypes = []interface{}{
	(*EventProcessingResult)(nil),              // 0: event_processing.EventProcessingResult
	(*pipeline_data.BatchProcessingEvent)(nil), // 1: pipeline_data.BatchProcessingEvent
}
var file_event_processing_proto_depIdxs = []int32{
	1, // 0: event_processing.EventProcessor.ProcessBatch:input_type -> pipeline_data.BatchProcessingEvent
	0, // 1: event_processing.EventProcessor.ProcessBatch:output_type -> event_processing.EventProcessingResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_processing_proto_init() }
func file_event_processing_proto_init() {
	if File_event_processing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_processing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventProcessingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_processing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_processing_proto_goTypes,
		DependencyIndexes: file_event_processing_proto_depIdxs,
		MessageInfos:      file_event_processing_proto_msgTypes,
	}.Build()
	File_event_processing_proto = out.File
	file_event_processing_proto_rawDesc = nil
	file_event_processing_proto_goTypes = nil
	file_event_processing_proto_depIdxs = nil
}
