// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: event_processing.proto

package event_processing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pipeline_data "project/grpc-proto/pipeline_data"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventProcessorClient is the client API for EventProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventProcessorClient interface {
	ProcessBatch(ctx context.Context, in *pipeline_data.BatchProcessingEvent, opts ...grpc.CallOption) (*EventProcessingResult, error)
}

type eventProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewEventProcessorClient(cc grpc.ClientConnInterface) EventProcessorClient {
	return &eventProcessorClient{cc}
}

func (c *eventProcessorClient) ProcessBatch(ctx context.Context, in *pipeline_data.BatchProcessingEvent, opts ...grpc.CallOption) (*EventProcessingResult, error) {
	out := new(EventProcessingResult)
	err := c.cc.Invoke(ctx, "/event_processing.EventProcessor/ProcessBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventProcessorServer is the server API for EventProcessor service.
// All implementations must embed UnimplementedEventProcessorServer
// for forward compatibility
type EventProcessorServer interface {
	ProcessBatch(context.Context, *pipeline_data.BatchProcessingEvent) (*EventProcessingResult, error)
	mustEmbedUnimplementedEventProcessorServer()
}

// UnimplementedEventProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedEventProcessorServer struct {
}

func (UnimplementedEventProcessorServer) ProcessBatch(context.Context, *pipeline_data.BatchProcessingEvent) (*EventProcessingResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedEventProcessorServer) mustEmbedUnimplementedEventProcessorServer() {}

// UnsafeEventProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventProcessorServer will
// result in compilation errors.
type UnsafeEventProcessorServer interface {
	mustEmbedUnimplementedEventProcessorServer()
}

func RegisterEventProcessorServer(s grpc.ServiceRegistrar, srv EventProcessorServer) {
	s.RegisterService(&EventProcessor_ServiceDesc, srv)
}

func _EventProcessor_ProcessBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pipeline_data.BatchProcessingEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventProcessorServer).ProcessBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_processing.EventProcessor/ProcessBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventProcessorServer).ProcessBatch(ctx, req.(*pipeline_data.BatchProcessingEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// EventProcessor_ServiceDesc is the grpc.ServiceDesc for EventProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_processing.EventProcessor",
	HandlerType: (*EventProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBatch",
			Handler:    _EventProcessor_ProcessBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event_processing.proto",
}
